### ISSUE TITLE
can't run command twice

### ISSUE THREAD

**Issue by thewindsofwinter** [thewindsofwinter/frac-kawaii#1]
running $frakawaii twice on a server crashes with weird tensorflow shenanigans:

```
Ignoring exception in command frakawaii:
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\discord\ext\commands\core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "C:\Users\reson\frakawaii\frac-kawaii\special.py", line 57, in frakawaii
    net = FasterRCNNSlim()
  File "C:\Users\reson\frakawaii\frac-kawaii\faster_rcnn_wrapper.py", line 39, in __init__
    net_conv = conv2d_same(self._image, 64, 7, stride=2, scope='conv1')
  File "C:\Users\reson\frakawaii\frac-kawaii\tf_contrib\resnet_utils.py", line 138, in conv2d_same
    return layers_lib.conv2d(
  File "C:\Users\reson\frakawaii\frac-kawaii\tf_contrib\arg_scope.py", line 182, in func_with_args
    return func(*args, **current_args)
  File "C:\Users\reson\frakawaii\frac-kawaii\tf_contrib\layers.py", line 1139, in convolution2d
    return convolution(
  File "C:\Users\reson\frakawaii\frac-kawaii\tf_contrib\arg_scope.py", line 182, in func_with_args
    return func(*args, **current_args)
  File "C:\Users\reson\frakawaii\frac-kawaii\tf_contrib\layers.py", line 1057, in convolution
    outputs = layer.apply(inputs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\keras\engine\base_layer_v1.py", line 1697, in apply
    return self.__call__(inputs, *args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\keras\legacy_tf_layers\base.py", line 568, in __call__
    outputs = super(Layer, self).__call__(inputs, *args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\keras\engine\base_layer_v1.py", line 764, in __call__
    self._maybe_build(inputs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\keras\engine\base_layer_v1.py", line 2086, in _maybe_build
    self.build(input_shapes)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\keras\layers\convolutional.py", line 201, in build
    self.kernel = self.add_weight(
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\keras\legacy_tf_layers\base.py", line 455, in add_weight
    variable = super(Layer, self).add_weight(
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\keras\engine\base_layer_v1.py", line 442, in add_weight
    variable = self._add_variable_with_custom_getter(
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\training\tracking\base.py", line 873, in _add_variable_with_custom_getter
    new_variable = getter(
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 1616, in get_variable
    return get_variable_scope().get_variable(
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 1326, in get_variable
    return var_store.get_variable(
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 580, in get_variable
    return custom_getter(**custom_getter_kwargs)
  File "C:\Users\reson\frakawaii\frac-kawaii\tf_contrib\layers.py", line 1761, in layer_variable_getter
    return _model_variable_getter(getter, *args, **kwargs)
  File "C:\Users\reson\frakawaii\frac-kawaii\tf_contrib\layers.py", line 1739, in _model_variable_getter
    return variables.model_variable(
  File "C:\Users\reson\frakawaii\frac-kawaii\tf_contrib\arg_scope.py", line 182, in func_with_args
    return func(*args, **current_args)
  File "C:\Users\reson\frakawaii\frac-kawaii\tf_contrib\variables.py", line 338, in model_variable
    var = variable(
  File "C:\Users\reson\frakawaii\frac-kawaii\tf_contrib\arg_scope.py", line 182, in func_with_args
    return func(*args, **current_args)
  File "C:\Users\reson\frakawaii\frac-kawaii\tf_contrib\variables.py", line 270, in variable
    return getter(
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 535, in _true_getter
    return self._get_single_variable(
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 898, in _get_single_variable
    raise ValueError("%s Originally defined at:\n\n%s" %
ValueError: Variable resnet_v1_101/conv1/weights already exists, disallowed. Did you mean to set reuse=True or reuse=tf.AUTO_REUSE in VarScope? Originally defined at:

  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 2133, in __init__
    self._traceback = tf_stack.extract_stack_for_node(self._c_op)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 3754, in _create_op_internal
    ret = Operation(
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 797, in _apply_op_helper
    op = g._create_op_internal(op_type_name, inputs, dtypes=None,
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\ops\gen_state_ops.py", line 1750, in variable_v2
    _, _, _op, _outputs = _op_def_library._apply_op_helper(
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\ops\state_ops.py", line 70, in variable_op_v2
    return gen_state_ops.variable_v2(


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\discord\ext\commands\bot.py", line 939, in invoke
    await ctx.command.invoke(ctx)
  File "C:\ProgramData\Anaconda3\lib\site-packages\discord\ext\commands\core.py", line 863, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\discord\ext\commands\core.py", line 94, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: ValueError: Variable resnet_v1_101/conv1/weights already exists, disallowed. Did you mean to set reuse=True or reuse=tf.AUTO_REUSE in VarScope? Originally defined at:

  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 2133, in __init__
    self._traceback = tf_stack.extract_stack_for_node(self._c_op)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 3754, in _create_op_internal
    ret = Operation(
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 797, in _apply_op_helper
    op = g._create_op_internal(op_type_name, inputs, dtypes=None,
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\ops\gen_state_ops.py", line 1750, in variable_v2
    _, _, _op, _outputs = _op_def_library._apply_op_helper(
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\ops\state_ops.py", line 70, in variable_op_v2
    return gen_state_ops.variable_v2(

Traceback (most recent call last):
  File "C:\Users\reson\frakawaii\frac-kawaii\main.py", line 32, in <module>
    bot.run(os.environ["DISCORD_TOKEN"])
  File "C:\ProgramData\Anaconda3\lib\site-packages\discord\client.py", line 723, in run
    return future.result()
  File "C:\ProgramData\Anaconda3\lib\site-packages\discord\client.py", line 702, in runner
    await self.start(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\discord\client.py", line 666, in start
    await self.connect(reconnect=reconnect)
  File "C:\ProgramData\Anaconda3\lib\site-packages\discord\client.py", line 566, in connect
    await self.ws.poll_event()
  File "C:\ProgramData\Anaconda3\lib\site-packages\discord\gateway.py", line 582, in poll_event
    raise ConnectionClosed(self.socket, shard_id=self.shard_id, code=code) from None
discord.errors.ConnectionClosed: Shard ID None WebSocket closed with 4004
```

**Comment by thewindsofwinter** [comment]
@veryboi do u think u can look into this? or should I
